#ifndef DEFAULTS_H
#define DEFAULTS_H

const char* const json_data =
"{"
"    \"data\": ["
"        {"
"            \"color\": 3,"
"            \"diam\": 4,"
"            \"img64\": \"a\","
"            \"len\": 5,"
"            \"price\": 3,"
"            \"type\": \"Simple Dildo\""
"        },"
"        {"
"            \"color\": 3,"
"            \"diam\": 4,"
"            \"diam2\": 6,"
"            \"img64\": \"b\","
"            \"len\": 5,"
"            \"price\": 3,"
"            \"type\": \"Double Dildo\""
"        },"
"        {"
"            \"color\": 3,"
"            \"diam\": 14,"
"            \"img64\": \"c\","
"            \"len\": 15,"
"            \"price\": 13,"
"            \"temp\": 17,"
"            \"type\": \"Thermo Dildo\","
"            \"watts\": 16"
"        },"
"        {"
"            \"color\": 3,"
"            \"diam\": 24,"
"            \"freq\": 27,"
"            \"img64\": \"d\","
"            \"len\": 25,"
"            \"price\": 23,"
"            \"type\": \"Internal Vibrator\","
"            \"watts\": 26"
"        },"
"        {"
"            \"color\": 3,"
"            \"diam\": 34,"
"            \"freq\": 37,"
"            \"img64\": \"e\","
"            \"len\": 35,"
"            \"price\": 33,"
"            \"temp\": 36,"
"            \"type\": \"Dildo Deluxe\","
"            \"watts\": 36"
"        }"
"    ],"
"    \"len\": 5"
"}"
;

#endif // DEFAULTS_H
